apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: preview-pr-5

resources:
  - rollout.yaml
  - service-active.yaml
  - service-preview.yaml
  - serviceaccount.yaml

commonAnnotations:
  preview.argocd.io/pr-number: "5"
  preview.argocd.io/branch: "feature-cambio3"
  preview.argocd.io/head-sha: "8844810018599232aacdd7a0a7b9ed9fd2dd60a3"
  preview.argocd.io/image-digest: "sha256:549c8ee3e9196b8eeadb2aeb8c2d64918d4834d243c2799e1d2c6030fe633801"
