apiVersion: apps/v1
kind: Deployment
metadata:
  name: landingpage
  labels:
    app: landingpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landingpage
  template:
    metadata:
      labels:
        app: landingpage
    spec:
      containers:
        - name: landing
          image: juanmarulanda/landingpocargoprpreview@sha256:ea511a1ab9561713b0b27cb87790d82af8c8254a81afe862b29e746636eb8e03
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
