apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: landing-prod

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: landingpage-content
    files:
      - site/index.html
      - site/style.css

commonLabels:
  release.argocd.io/source-sha: "4ab4a5cdfec24bd2ec00ad8765d300b72465029f"

generatorOptions:
  disableNameSuffixHash: true
