apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: landing-prod

resources:
  - deployment.yaml
  - service.yaml

commonAnnotations:
  release.argocd.io/source-sha: "7896b85ca381903be55f300fa686506e5c400744"
  release.argocd.io/image-digest: "sha256:ac890512412be3f6cd20568ea5543c4e565f0739b5a859925f7810f4da29c316"
