apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: landing-prod

resources:
  - rollout.yaml
  - service-active.yaml
  - service-preview.yaml

commonAnnotations:
  release.argocd.io/source-sha: "3390d75c47c4d252cb9949478990549af83ef740"
  release.argocd.io/image-digest: "sha256:d7ae9303db980fef361417b3d23dd1234d32dfa2c3cf35474c7bf6f9634d6f29"
