apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: landingpage
  labels:
    app: landingpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landingpage
  strategy:
    blueGreen:
      activeService: landingpage-active
      previewService: landingpage-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
  template:
    metadata:
      labels:
        app: landingpage
    spec:
      containers:
        - name: landing
          image: juanmarulanda/landingpocargoprpreview@sha256:d7ae9303db980fef361417b3d23dd1234d32dfa2c3cf35474c7bf6f9634d6f29
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
