apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: landingpage
  labels:
    app: landingpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landingpage
  strategy:
    blueGreen:
      activeService: landingpage-active
      previewService: landingpage-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
  template:
    metadata:
      labels:
        app: landingpage
    spec:
      containers:
        - name: landing
          image: juanmarulanda/landingpocargoprpreview@sha256:06408d3d41096e89f7f9ed2ccd16e1648a8b8959cb1f52751a80335d5b37e123
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
