apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: landingpage
  labels:
    app: landingpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landingpage
  strategy:
    blueGreen:
      activeService: landingpage-active
      previewService: landingpage-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
  template:
    metadata:
      labels:
        app: landingpage
    spec:
      containers:
        - name: landing
          image: juanmarulanda/landingpocargoprpreview@sha256:4bd65eb15283e9309902ad8d642d342b39fd68a33ac97aa1f685ed3b75527042
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
