apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: landing-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ju4nr3v0l/InfraPOCArgoPUllRequestGenerator.git
    targetRevision: main
    path: generated/environments/prod/landing
  destination:
    server: https://kubernetes.default.svc
    namespace: landing-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
