apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: landing-pr-previews
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - pullRequest:
        github:
          owner: ju4nr3v0l
          repo: landingPOCArgoPUllRequestGenerator
          tokenRef:
            secretName: github-token
            key: token
          labels:
            - preview
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'landing-pr-{{.number}}'
      labels:
        app.kubernetes.io/part-of: landing-pr-previews
        app.kubernetes.io/managed-by: argocd-applicationset-controller
    spec:
      project: default
      source:
        repoURL: 'https://github.com/ju4nr3v0l/landingPOCArgoPUllRequestGenerator.git'
        targetRevision: '{{.head_sha}}'
        path: k8s/preview
        kustomize:
          nameSuffix: '-pr-{{.number}}'
          commonLabels:
            preview.argocd.io/pr-number: '{{.number}}'
            preview.argocd.io/branch: '{{.branch_slug}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'preview-pr-{{.number}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
