apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: landing-pr-previews
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: 'https://github.com/ju4nr3v0l/InfraPOCArgoPUllRequestGenerator.git'
        revision: main
        directories:
          - path: generated/previews/*
  template:
    metadata:
      name: 'landing-{{.path.basename}}'
      labels:
        app.kubernetes.io/part-of: landing-pr-previews
        app.kubernetes.io/managed-by: argocd-applicationset-controller
    spec:
      project: default
      source:
        repoURL: 'https://github.com/ju4nr3v0l/InfraPOCArgoPUllRequestGenerator.git'
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'preview-{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
