apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: preview-pr-4

resources:
  - rollout.yaml
  - service-active.yaml
  - service-preview.yaml
  - serviceaccount.yaml

commonAnnotations:
  preview.argocd.io/pr-number: "4"
  preview.argocd.io/branch: "feature-cambio3"
  preview.argocd.io/head-sha: "359dc7bde651448e073fc5c51980a2f587ddd113"
  preview.argocd.io/image-digest: "sha256:bbcefddbe833d418b0de7d58e39f3167ac5417c9e2294d40575cb4e5803dd3ef"
