apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: preview-pr-4

resources:
  - rollout.yaml
  - service-active.yaml
  - service-preview.yaml
  - serviceaccount.yaml

commonAnnotations:
  preview.argocd.io/pr-number: "4"
  preview.argocd.io/branch: "feature-cambio3"
  preview.argocd.io/head-sha: "78d62150948e57ca3c13e5f7465b49a72679052a"
  preview.argocd.io/image-digest: "sha256:6dafa8ec7f9551f27ec6937d0517c32022852f74d9d5865d81bbfffad19a06ab"

nameSuffix: "-pr-4"
